### ISSUE TITLE
Authorization mechanism not supported.

### ISSUE THREAD

**Issue by modeler** [ravsau/aws-labs#4]
Signed URLs created using this method no longer work as described, the error message returned by S3 is:

> The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>6E3C22BA95E2D831</RequestId><HostId>GahUHTZ6yXzUhEOl+AtneMlUiv6MgvIMG0n/lyDwv3rwPr/CHxCvuwR7ds3FtZeJ8t1rQOgNUpA=</HostId></Error>
```

I assume some further tweaking needs to be done, but I haven't found out what yet.

**Comment by ravsau** [comment]
Hi @modeler If this is regarding this lab **presign-url-s3-upload**, I just verified the steps and it's working for me.

**Comment by ravsau** [comment]
I'll share a couple of links that have some pointers on what you can try to make this work : 
- https://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4
- https://stackoverflow.com/questions/43985866/boto-error-in-scrapy-the-authorization-mechanism-you-have-provided-is-not-supp

**Comment by ravsau** [comment]
This may be the reason why your upload is failing 
![image](https://user-images.githubusercontent.com/22568316/55692230-e1728280-5973-11e9-9f51-d90b8f3d72b4.png)


## Reference 
https://docs.aws.amazon.com/general/latest/gr/signature-version-2.html

**Comment by shubhamsre** [comment]
You should set signatureVersion: 'v4' in config to use new signature version in aws:
AWS.config.update
                           ({
    signatureVersion: 'v4'
                            });

If you are using boto3 then there will be a different work around. But the error is just because the region doesn't support V2 and V4 must be used.

**Comment by modeler** [comment]
Hi,

Thank you both for following this up. I just tried again and it worked fine, no idea what the problem was on my previous attempt!

**Comment by shubhamsre** [comment]
> Hi,
> 
> Thank you both for following this up. I just tried again and it worked fine, no idea what the problem was on my previous attempt!

Your welcome @modeler and Its great to hear that. Anyway just clone the repo again as i made the changes to work only with V4. I am sure it will work just fine.
Thanks
